const SubmitInfo = {
  region: "",
  gender: "",
  age: 0,
  income: 0,
  education: "",
  industry: "",
  workRole: "",
  employment: "",
  entrepreneur: "",
  workSite: "",
  covidReact: "",
  PQ_ShortScale: 0,
  ROAMG_ShortScale: 0,
  IN_ShortScale: 0,
  relentlessResult: 0,
  relentless1: 0,
  relentless2: 0,
  relentless3: 0,
  oppositionalResult: 0,
  oppositional1: 0,
  oppositional2: 0,
  oppositional3: 0,
  agnosticResult: 0,
  agnostic1: 0,
  agnostic2: 0,
  agnostic3: 0,
  messianicResult: 0,
  messianic1: 0,
  messianic2: 0,
  messianic3: 0,
  gallantResult: 0,
  gallant1: 0,
  gallant2: 0,
  gallant3: 0,
  insecureResult: 0,
  insecure1: 0,
  insecure2: 0,
  insecure3: 0,
  nutsResult: 0,
  nuts1: 0,
  nuts2: 0,
  nuts3: 0,
};

export default SubmitInfo;
